image: 
  name: hashicorp/terraform:latest
  entrypoint: [""]

stages:
  - validate
  - plan

terraform_validate:
  stage: validate
  script:
    - terraform init -backend=false
    - terraform fmt -check
    - terraform validate

terraform_plan:
  stage: plan
  script:
    - terraform init
    - terraform plan