image: 
  name: hashicorp/terraform:latest
  entrypoint: [""]

stages:
  - validate
  - plan
  - apply
  - destroy

terraform_validate:
  stage: validate
  script:
    - terraform init -backend=false
    - terraform fmt -check
    - terraform validate

terraform_plan:
  stage: plan
  script:
    - terraform init
    - terraform plan

terraform_apply:
  stage: apply
  script:
    - terraform init
    - terraform apply -auto-approve

terraform_destroy:
  stage: destroy
  script:
    - terraform init
    - terraform destroy -auto-approve
  when: manual

variables:
  TF_HTTP_USERNAME: gitlab-ci-token
  TF_HTTP_PASSWORD: ${CI_JOB_TOKEN}